### ISSUE TITLE
Malten corrections (German words/bot tags)

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/PWK#101]
@maltenth expressed an interest in resolving the spelling variations seen in the text of the `<bot>` tags in pwk.

Here is an 'hk' version of pw.
[pw_hk.zip](https://github.com/sanskrit-lexicon/PWK/files/13340652/pw_hk.zip)
(Note this is based on csl-orig/v02/pw/pw.txt at commit d847fe33dd4e2626ebf8869325e0bca452a5f20d)

**Comment by funderburkjim** [comment]
## bot frequency data

* [bot_freq_pw_0.txt](https://github.com/sanskrit-lexicon/PWK/blob/master/pwkissues/issue101/bot_freq_pw_0.txt) frequency count for bot tags in pw
* [bot_freq_mw.txt](https://github.com/sanskrit-lexicon/PWK/blob/master/pwkissues/issue101/bot_freq_mw.txt) similar list for mw dictionary
* [bot_freq_pw_0_withmw.txt](https://github.com/sanskrit-lexicon/PWK/blob/master/pwkissues/issue101/bot_freq_pw_0_withmw.txt)  frequency count for bot tags in pw, with corresponding counts in mw.

**Comment by funderburkjim** [comment]
## German word corrections.

See [german directory](https://github.com/sanskrit-lexicon/PWK/tree/master/pwkissues/issue101/german).
* [thomas changes](https://github.com/sanskrit-lexicon/PWK/blob/master/pwkissues/issue101/german/corrections_from_thomas_skype.txt)  the starting point
* [change_pw_2.txt](https://github.com/sanskrit-lexicon/PWK/blob/master/pwkissues/issue101/german/change_pw_2.txt) and [change_pw_3.txt](https://github.com/sanskrit-lexicon/PWK/blob/master/pwkissues/issue101/german/change_pw_3.txt)  change files with annotations.  161 lines of pw.txt changed.  These changes now installed in csl-orig repository (csl-orig/v02/pw/pw.txt).
* [unchanged.txt](https://github.com/sanskrit-lexicon/PWK/blob/master/pwkissues/issue101/german/unchanged.txt) 15 items from Thomas changes that did not generate changes to pw.txt.  Have asked @maltenth to review.

**Comment by funderburkjim** [comment]
Have heard from @maltenth  -- He intends to work on the botanical names in pwk.

**Comment by Andhrabharati** [comment]
Nice to hear this, @funderburkjim !

Incidentally, it may be of some interest that while MW has just 45 unique instances incl. the Botanist's names, pwk has more than 4 times of that (~190).

More interesting is that PWG has many a times has only the Botanist's name separately, with a different Sanskrit name of the plant/tree **having the same Sc. name**, **in contrast to the current entry name**.

And should we have the Botanist's names also expanded somewhere? 
It is seen that over 50 such names occur in just these three works (PWG, pwk and MW).

**Comment by Andhrabharati** [comment]
Another observation:

While MW has >80% of `<bot>`-entries with 2nd (or later) words with Cap. letter, while pwk has just <30% of such.

So the Capitalisation being made THE 'norm' in the Sc. names across the CDSL works "stands" debatable!!

**Comment by Andhrabharati** [comment]
> Incidentally, it may be of some interest that while MW has just 45 unique instances incl. the Botanist's name(s), pwk has more than 4 times of that (~190).

See what G.J. Meulenbeld says reg. this--

![image](https://github.com/sanskrit-lexicon/PWK/assets/75209130/fc1f42dd-a658-4329-8bf2-970ffb8e6984)

**Comment by Andhrabharati** [comment]
Here is the quick summary of counts--

![image](https://github.com/sanskrit-lexicon/PWK/assets/75209130/474f6b75-3133-4a52-ad9c-6c13d1528457)

In pwk, I had opted **NOT** to have the Capitalisation.

My work on MW markup has helped a lot in marking (or changing from bot to zoo) the additional <zoo words (these could not be marked so earlier, as they were not clearly **identifiable** in pwk 'as-is').

**Comment by Andhrabharati** [comment]
BTW, I've found some more 'grouped' entries in pwk now.

**Comment by funderburkjim** [comment]
@Andhrabharati   Am working with Thomas on the bot issue.
Will report here when the time appears right to do so.

**Comment by funderburkjim** [comment]
Closing this issue, since I have been unable to reach @maltenth since 8/24/2024.
In April 2024 I did some work on the botanical names, and will present that work in another issue.
