### ISSUE TITLE
Pure numbers in references

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/PWK#11]
@funderburkjim and @gasyoun ,

When I started meddling with pw.xml for generation of bibliography list,
I came across many references which were purely numbers.

See [html](http://www.sanskrit-lexicon.uni-koeln.de/scans/PWScan/2014/web/webtc/indexcaller.php?key=aMSa&input=slp1&output=SktDevaUnicode) and [pdf](http://www.sanskrit-lexicon.uni-koeln.de/scans/PWScan/2014/web/webtc/servepdf.php?page=1001) of 'aMSa'.
Look at  `Theil: स्वंशातस्  139,1.`

How do we decipher such references ?

Is there something in the preface which says how to go about them ?

**Comment by gasyoun** [comment]
Not that I remember. Will reread the Preface and let you know.

**Comment by funderburkjim** [comment]
It is common in MW to see such 'pure number' references, where the abbreviation of the work is omitted;  and there the interpretation is that the omitted work is *the previously mentioned work*.

However, this doesn't seem to apply to the aMSa example in PW.

**Comment by gasyoun** [comment]
Yeah, I was thinking about `the previously mentioned work` model as well. Can we "add" that data in MW "pure numbers" in a meta-tag without much pain? I'm thinking about another book by Boethlingk in PW references, but nothing matches.

**Comment by funderburkjim** [comment]
Re 'add that data as meta-tag in MW ... without much pain'

No, WITH much pain.   

Here are likely steps involved:
step 1.  Decide on a markup extension to 'ls'. 
   ```
Here is an example (under headword 'De':
<ls>Pa1n2._2-4_,_78_;_iii_,_1_,_49</ls>~;~<ab>Prec.</ab>~<s>DeyAt</s>~,~
<ls>vi_,_4_,_67</ls>~

   which could be changed to 

<ls>Pa1n2._2-4_,_78_;_iii_,_1_,_49</ls>~;~<ab>Prec.</ab>~<s>DeyAt</s>~,~
<ls implied="Pa1n2.">vi_,_4_,_67</ls>~
   ```
step 2.  Identify the cases that need the implied  literary source, and deduce the implied value
of the `implied` attribute (such as "Pa1n2").  I estimate this to be a difficult programming task
step 3.  Change various aspects of the display program for MW to recognize the enhancement.

**Comment by Andhrabharati** [comment]
@drdhaval2785

@thomasincambodia has mentioned, in one of the issues recently, that such instances refer to Boethlingk's Ind. Spr.

As such, this issue could be closed now.

**Comment by thomasincambodia** [comment]
> @drdhaval2785
> 
> @thomasincambodia has mentioned, in one of the issues recently, that such instances refer to Boethlingk's Ind. Spr.
> 
> As such, this issue could be closed now.

@Andhrabharati 
If this refers to "pure numbers" source references in Boehtlingk's pwk the reference is to Boe**ht**lingk's Chrestomathie.

**Comment by Andhrabharati** [comment]
Thanks Thomas,

I had forgotten the name "Chr." and mistaken it to be the ongoing "Ind. Spr." work.

**Comment by gasyoun** [comment]
> I had forgotten the name "Chr." and mistaken it to be the ongoing "Ind. Spr." work.

Right, closable now indeed,
