### ISSUE TITLE
BHĀGAVATAPURĀṆA PWKVN literary source markup

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/PWK#110]
Apply the methods of #109 to the cdsl 'dictionary' pwkvn.
212 matches in 196 lines for "BHĀG. P." in buffer: pwkvn.txt

**Comment by funderburkjim** [comment]
## changes made
Work in [issue110 directory](https://github.com/sanskrit-lexicon/PWK/tree/master/pwkissues/issue110).

See change_1.txt for the only (2) changes made.
Closing this issue.

**Comment by Andhrabharati** [comment]
@funderburkjim 

The correction in line 20255 
from `<ls>BHĀG. P. 2,9,34</ls>. <ls n="BHĀG. P.">7,49,4</ls>.`
to `<ls>BHĀG. P. 2,9,34</ls>. <ls n="BHĀG. P.">2,9,34</ls>.`
is bad (being the repetition of the same verse)!!

Either you have to make the 2nd one as "**7,12,15**" or as "**10,3,14**", or [delete it altogether](https://github.com/sanskrit-lexicon/PWK/issues/109#issuecomment-2525306099).

**Comment by funderburkjim** [comment]
> make the 2nd one as "7,12,15" ...

Done for pwkvn

**Comment by funderburkjim** [comment]
> make the 2nd one as "7,12,15" ...

Done for pw
