### ISSUE TITLE
enhancement to makeabbrv

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/PWK#16]
The [readme.md of pw_dhaval](https://github.com/sanskrit-lexicon/PWK/blob/master/pw_ls/pw_dhaval/readme.md)  describes how to get the required data file pw.xml by running a simple script. 

Then,  [makeabbrv.sh](https://github.com/sanskrit-lexicon/PWK/blob/master/pw_ls/pw_dhaval/abbrvwork/makeabbrv.sh) can be rerun to use the new pw.xml.  Also, makeabbrv.sh checks to see whether pw.xml is in the expected location, and exits, with
a helpful message, if pw.xml is not found where expected.

**Comment by drdhaval2785** [comment]
Documented what it needed to. Time to go to sleep.
