### ISSUE TITLE
¯BÜHLER,Rep. corrections

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/PWK#33]
When I searched for 
`¯BÜHLER,Rep.No.`
There are 299 such occurrences.

In my opinion, it should be `¯BÜHLER,Rep. No.` with a space in between.
![capture](https://cloud.githubusercontent.com/assets/5755132/11912372/29344bdc-a660-11e5-9d9e-18fec3ee0923.PNG)
¯BÜHLER,Rep. is the work and No. is the entry number.
Not sure.
So kept as a separate issue.

**Comment by funderburkjim** [comment]
@drdhaval2785 
I solved matching to BÜHLER,Rep.  by an adjustment to abbrv.py (line 138 of current version).  
This change has the effect of dropping the 'No,'  when abbrv.py generates the abbreviation to be
matched.

**Comment by gasyoun** [comment]
Agree with @funderburkjim
