### ISSUE TITLE
'ls' starting with a number

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/PWK#40]
Taking a clue from https://github.com/sanskrit-lexicon/PWK/issues/39#issue-123499546, it makes sense if we examine the references starting with a number.

We need to understand their pattern and come out with some better explanation and display for them.

This issue is devoted to their study.

**Comment by Andhrabharati** [comment]
@drdhaval2785

With Jim's recent work on pwk ls updation (taking the AB version as a guide), this issue is out-dated and could be closed now.
