### ISSUE TITLE
crefminusbib - fuzzymatch1

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/PWK#53]
This applies the general levenshtein  fuzzy-distance concept to the problem of matching abbreviations of literary sources from pw.txt to the abbreviations of reference works in the pw bibliography.

Specifically,  it takes all the thus far  (through #45) unmatched references appearing in [crefminusbib.txt](https://github.com/sanskrit-lexicon/PWK/blob/master/pw_ls/pwbib/crefminusbib.txt).  There are 1621 of these .

And it uses the [pwbib_abbrv_all.txt](https://github.com/sanskrit-lexicon/PWK/blob/master/pw_ls/pwbib/pwbib_abbrv_all.txt) list of abbreviations from pwbib0, including those that are additional references (pwbib_new) and previously identified 'unused' abbreviations.
There are 522 of these.

For each crefminusbib abbreviation X,  an 'edit-distance' D is computed with each known abbreviation Y.  
 If D is <= **2** (a parameter that could be adjusted in later runs), then Y is added to the list S of suggestions for X.

Finally, for each X a result is posted to one of three output files:

* (618) [likely.txt](https://github.com/sanskrit-lexicon/PWK/blob/master/pw_ls/pwbib/fuzzymatch1/likely.txt) if 
  * There is exactly 1 suggestion Y for X
  * and X has 4 or more characters.  (using edit distance is not reliable for comparing short strings)
     * The reason for this second condition is that I noticed that MAT-MIT was a suggestion, but
        the 'MAT  is, at least in a few cases, part of a more complex garbling of 'Mat.med'.
* (186) [maybe.txt](https://github.com/sanskrit-lexicon/PWK/blob/master/pw_ls/pwbib/fuzzymatch1/maybe.txt) if there is 1 or more suggestions, but X has not already been written to likely.txt
* (817) [nomatch.txt](https://github.com/sanskrit-lexicon/PWK/blob/master/pw_ls/pwbib/fuzzymatch1/nomatch.txt)  if D exceeds the threshold ('2') of suggestion distance.

I am tempted to generate corrections based on the 618 likely cases.  My hunch is that these are
almost surely pw.txt typos and that the likely suggestion is the correct correction for the typo.

But will wait a day or so until I and others have had a chance to look for 'false positives' (like MAT-MIT) in that list of 618.

When these likely cases (as possibly amended by our eyeball examination) are implemented as
pw corrections, I'll take a look at further ways to program generation of highly likely corrections.

**Comment by drdhaval2785** [comment]
It is a good resource.

Regarding likely case generation prepositions, the objectionable entries are 
```
GARUD2A:GAUD2AP:not a reference. Proper name garuqa

```

**Comment by funderburkjim** [comment]
Added VAIDJAKA to pwbib_new, since the printed form (Large initial capital letter + small capital letters) is like that of references.

A small number (4) of non-matches due to a bug in pwbib_new.  For instance, 
`SIDDH.K.ed.TA7R.` appeared in pwbib_new with ending period.  This kept it from matching to
the sortedcref abbreviations, where the period has been removed. Thus these four have been 
removed from corrections based on likely.txt:
```
    102:K4AKR.zu.SUC2R:K4AKR.zu.SUC2R.
    251:R.ed.Bomb:R.ed.Bomb.
    578:NR2S.TA7P.UP:NR2S.TA7P.UP.
    608:SIDDH.K.ed.TA7R:SIDDH.K.ed.TA7R.
```

**Comment by gasyoun** [comment]
Other than these few changes the list is ready to be installed.

```
GOLEBR:GOP.BR -> COLEBR.Alg.
<ls>GOLEBR.</ls> <noti>Alg. 228.</noti> -> COLEBR.Alg.

KERN:KIR -> leave as is
KRRN:KIR -> leave as is

SIDDH.K:SADDH.P -> SIDDH.K.
TANTRAS:TATTVAS -> leave as is
MANU:KAN2 -> leave as is

VIKRAM:VIRAM -> leave as is
EBEN:WEBER -> ordinary German word, no source here quoted
HALL.N:MALLIN -> HALL in (in = inside, ordinary German word)
```

**Comment by funderburkjim** [comment]
Some more false positives:
```
¯SIDDH.K.@¯SADDH.P.   add SIDDH.K to pwbib_new
¯SATJA.@¯SA7J.   add SATJA to pwbib_new
¯SV.FUR.@¯SV.A7R.  -> ¯SV. ‹für›
¯TRIPR.@¯TRIK. 3 instances.  Related to .GAN2IT.TRIPR.
¯VAIC2JA.@¯VIC2VA  not a reference.
¯VIKRAM.@¯VIRAM  once only, print change to the common ref. VIKRAMA7N5KAK4
¯VISHN2U.@¯VISHN2US.  Not sure. Not changing for now. See image below
```
![image](https://cloud.githubusercontent.com/assets/6393033/12101824/cf496100-b304-11e5-9117-f6086f90ed3c.png)

```
¯VJA7SA.@¯VA7SAV.  (3 times)  Always as ¯VJA7SA ‹zu› ¯JOGAS..  Adding as new source for now.
¯KALP.@¯KAP.  should be Devanagari #[kalp}
¯K4LAK.@¯K4AKR.  should be KA7LAK4
¯EBEN.@¯WEBER.  eben is German word
¯BHAR.@¯BHAG.  No change. Add to pwbib_new. Maybe same as BHARATA. hw = atyantara

```

**Comment by funderburkjim** [comment]
From @gasyoun 's list:   
```
KERN:KIR -> leave as is   Add KERN to pwbib_new
TANTRAS:TATTVAS -> leave as is   Add TANTRAS to pwbib_new
MANU:KAN2 -> leave as is   add MANU to pwbib_new

VIKRAM:VIRAM -> leave as is  see my note above
```
No additional comment on others, agree.

**Comment by funderburkjim** [comment]
Our three reviews now complete.  Thanks!

Will begin installation of changes.

**Comment by funderburkjim** [comment]
A few more false positives and other things noticed during installation:
```
¯AGHI@¯RAGH@t@   Part of a corruption of  AGNI-P (1 time)
¯BR2H.@¯R2V.  Clearly wrong. Solution will have to be done later.
¯C2AT. => ¯C2ATR.  Can't do this specific change, due to presence of C2AT.BR. Refinement needed.. The change needed is to ¯C2AT. ‹Br› ¯3,8,227.3,29. (hw = prasuta).
¯JOGAC2. => ¯JOGAS. is not right.
¯JOGAJ. => ¯JOGAS.   
   1. JOGAJ added to pwbib_new. Possibly yogayAjYavalkya
     {ditisutaguru}1{ditisutaguru}¦ •m. {%der Planet Venus%} ¯VARA7H.BR2H.23,6¯JOGAJ.6,7.
    2. Under hw sArvaBOma,
        ¯VJA7SA ‹zu› ¯JOGAJ.1,1.   This one Should be JOGAS
¯K4HA7ND. => ¯K4A7N2.  Can't do this everywhere, due to K4HA7ND.UP abbreviation.  There 
   are a few other cases, such as ¯K4HA7ND. ¯UP.
KA7VJA7D.@¯KA7VJA7L  add KA7VJA7D to pwbib_new, possibly kAvyAdarSa
KAUTUKAS.@¯KAUTUKAR  add KAUTUKAS to pwbib_new, possibly kOtukasarvasva
¯MAHA7BH. => ¯MAHA7B. (202 cases).  This is error in pwbib0, MAHA7BH is correct. No change to pw.
¯NAISH. => ¯NIGH.  (533 case). This also error in pwbib0.  NAISH is correct
¯NAIGH.@¯NIGH  (21 cases).  Added NAIGH to pwbib_new.  Possibly nEGaRwuka
¯VP^2.@¯VP.^2.   Odd, could not find this in pw.txt.  Maybe an artifact of abbrv.py (clean) ?

```   

Will have to continue installation tomorrow.

**Comment by drdhaval2785** [comment]
@funderburkjim 
A few more false positives.
```
C2AR:C2ATR:Correction in vEzRava is not proper. It is C2AT.BR. (SatapaTa brAhmaRa). Correction in PUwkAra headword is proper. It is C2ATR.
```

**Comment by drdhaval2785** [comment]
Eyeball examination of 5 letter entries
```
KRAKA:K4AKR:It is for K4ARAKA:<H1>500{kzar}1{kzar}¦ , #{kza/rati} ‹(metrisch auch› #{kzarate}) ‹und› #{*kzariti} ²1) {%fliessen , strömen ; von Wassern%} ‹u.s.w.› ²2) {%gleiten.%} ²3) {%zerfliessen , zerrinnen , schwinden , vergehen , zu Nichte werden.%} ²4) {%einer Sache%} (•Abl.) {%verlustig gehen.%} ²5) {%Etwas (•Acc.) strömen , ausströmen , giessen.%} #{mUtram} {%Urin entlassen%} ¯KRAKA.2,4. ²6) ‹ohne Object› {%einen Strom entlassen.%}
```

**Comment by gasyoun** [comment]
`¯VISHN2U.@¯VISHN2US.  Not sure. Not changing for now. See image below`
seems to be a print error to me, @drdhaval2785 ?

**Comment by funderburkjim** [comment]
Re 'PA7T:KA7T:' under SOkika.   PWBIB has `PAT. ZU P. == PATAN4G4ALI ZU PA7N2INI.`
   and the example is ` ¯PA7T. ‹zu.› ¯P.4,1.104.`.  So this must be print error for 
   ` ¯PAT.zuP.4,1.104.`  The form `¯PAT. ‹zu› ¯P.` is quite common (approx. 136 instances). in pw.txt, and should be
   changed to `¯PAT.zuP` to conform to pwbib0.  

Many of these are of the further form like `¯PAT. ‹zu› ¯P.1,1.4, ¯Va7rtt.1.6.`  

`Va7rtt. == Va7rttika.`  in pwbib.

 A small number (4) are like `¯PAT. ‹zu› ¯Va7rtt.1 ‹zu› ¯P.1,1,29.` which I am changing (as print change) to `¯PAT.zuP.1,1,29. ‹zu› ¯Va7rtt.1`  and similarly for the others.

Finally, there are 3 'naked' `¯PAT.` references.  I've added a PAT = PataYjali item to pwbib_new for these.

**Comment by funderburkjim** [comment]
From @drdhaval2785 's 5-letter list.

```
 ME.SH   
   ¯ME.SH.57.¯H.an.4,323   -> ¯MED.sh.57.H.an.4,323  
    add MED.sh to pwbib_new.  (no idea what it might be)
    Made 'H' as part of this reference.  It could be a separate reference (not in pwbib). Not sure.

K4LAK:K4AKR:to be changed to K4A7LAK4  . Minor difference, changed to KA7LAK4  (in pwbib0)

```

No additional comments. Agree with rest.

**Comment by funderburkjim** [comment]
Re `¯VISHN2U.@¯VISHN2US.`

For now, I'll put VISHN2U into pwbib_new, though it may be a print error and should be changed to
a non-reference 'Vishn2u'.

**Comment by funderburkjim** [comment]
Re `¯VP`  We have some variants.  At some earlier time, we discussed the use of 'VP.^2' in pwbib
and in pw.txt, and agreed that we should make use of the magic of unicode to represent both pwbib
and pw.txt more accurately as `¯VP.²` .
I've changed this in pwbib, and did an analysis of the cases in pw.txt, as follows:
```
1316 ¯VP    Total number of matches with this 3-character string. It partitions as follows:
 913 ¯VP.#  (# some digit)
   7 ¯VP.<space>
 268 ¯VP.^2   CHANGING to ¯VP.²
  93 ¯VP.²  Already the standard form, no change needed
  33 ¯VP².  CHANGING to ¯VP.²
   2  misc. errors

**Comment by funderburkjim** [comment]
Corrections now installed, and matching code rerun.

Here's the updated scorecard.
* Previous (#45): 66284 records of abbrvlist.txt that match out of 71827.0 (92.2%).
* Current: 69062 records of abbrvlist.txt that match out of 71170  (97.0%)

bibminuscref.txt still has 0 items.
There are 995 cases in crefminusbib.txt. (previously there were 1621).
