### ISSUE TITLE
Crefminus bib, the rest of them

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/PWK#57]
There are currently 927 cases mentioned in crefminusbib  (instances of literary source references whose abbreviations have not been matched with the bibliography).

Essentially, each of these is a 'special case'.

I've developed a good format for working with these, and have begun the correction identification process. The format is that of an Emacs Org mode file, which is quite convenient. Here's the way the first case looks:
```
* DONE CASE 001=WHITNEY.,Ind
;------------------------------------------------------------------------
; WHITNEY.,Ind 1 1
;Instance 1, hw=vizwIma, L=105426, [[http://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/servepdf.php?dict=PW&page=6136-1][page 6136-1]]
¯WHITNEY.,Ind.@vizwIma@@105426:¯WHITNEY,Ind.:t:
;<H1>000{vizwIma}1{vizwIma/}¦ ¯AV.20,135,5 ‹nach› ***¯WHITNEY.,Ind.*** PW105424
```

When viewing this file in Emacs Org mode, the link just shows up as a clickable link 
[page 6136-1](http://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/servepdf.php?dict=PW&page=6136-1)  which opens a browser tab.

The standard-form correction line can be edited as needed, and the pw.txt context is shown.

Most of the corrections are straightforward, a few require correction of context, and several new resources are identified, as well as adjustments needed to the clean_special abbrv.py code.

The reason for mentioning this as an issue is so that no one will duplicate effort on this task.

If anyone *does* want to  take on some of these separately,  I can provide a portion of the file.

Otherwise, I'll be tackling these over the next few weeks.

**Comment by drdhaval2785** [comment]
Best luck Jim. I would be out of touch till 5th february. I guess this work
would be over by then. If something is left over, I would be happ to help.

**Comment by gasyoun** [comment]
@funderburkjim no, go ahead. I can leave you my part as well.

> tackling these over the next few weeks.

@zaaf2 can we hope on you with PWK or PWG corrections still or are you out of the game?

I still see here many rude and simple mistakes, ones that should have been killed after fuzzy match.

> WEBLR.LIT

BURNELL,T.Richtig

> ABSCHIEDSKUSS

A

C2AM5K.EBEND
NI7LAK.SOLL
ROTH.VERMUTHET
GAUT.ANGEBLICH
{ARABISCH}
GAL.RICHTIG

**Comment by zaaf2** [comment]
@gasyoun I am afraid you will have to count me out. It has been very hard to find time lately. Only eventually perhaps I will be able to help, not systematically.

**Comment by gasyoun** [comment]
@funderburkjim after implementation of batch of my corrections I can take another look to ease your pain. `927` is a big number and I deal only with the easy ones, German mostly.

**Comment by funderburkjim** [comment]
@gasyoun   I appreciate the offer, but actually think it is better for me to do them, since I'm so 
familiar with the forms.  I'm at 26% currently.

If you have time to work on something,  I think #56  would be a good choice, especially since @zaaf2 has limited time now, and discovering titles for  the 'new' abbreviations is a task for which your knowledge of the literature would be an advantage.

**Comment by drdhaval2785** [comment]
This seems reasonable sharing of responsibility. And 26% is rather quick
Jim. Bes luck.

**Comment by gasyoun** [comment]
@funderburkjim that's a task too big, I will not accept it. First I need clean lists of headwords. Everything else - after. Otherwise I'll not make first volume till March with printed list of clean headwords. Hope still it can be finished one day.

**Comment by drdhaval2785** [comment]
@funderburkjim Interim update would be welcome.
I am anxious to know the percentage of work done by you from 927 list.

**Comment by funderburkjim** [comment]
I've gone through all of them, and installed and updated everything.

Somehow, the new crefminusbib still has 71 unresolved.  

Will work to resolve these tomorrow.

**Comment by funderburkjim** [comment]
Having trouble syncing.  CHanges not yet committed.

**Comment by drdhaval2785** [comment]
I havent committed anything in the interim. Not sure why there is problem
in syncing.

**Comment by funderburkjim** [comment]
I think you did a pwbib0 correction commit since my last sync.

Anyway, I recloned, installed my changes (to pwbib_new, abbrv.py, crefmatch.py);
then reran based on new pw.
Those are now committed to GitHub.

There are 75 unresolved in crefminusbib.

As mentioned, will work on resolving them tomorrow.

**Comment by gasyoun** [comment]
> FÜHRER.BR2H
> JOLIY.SCHULD
> NI7LAK.FASST

German words unsplit.

> SCHL
Schlegel.

**Comment by drdhaval2785** [comment]
@funderburkjim 
I congratulate you for completing this mammoth task single-handedly.
Once you cover the remaining 75, it would be a full fledged Ph.D. thesis coming to an end.
Good computational work on PW bibliography.

Best regards
