### ISSUE TITLE
Crefminus bib, the rest of them, part 2

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/PWK#59]
Finish the cases unresolved at https://github.com/sanskrit-lexicon/PWK/issues/57

**Comment by funderburkjim** [comment]
Made a small change to abbrv.py, so that 3 additional references move to purenumberabbrvlist.txt:
```
 6,2,85,Sch.
 2,S.40
 1,53(Thl.2,S.20).
```

**Comment by funderburkjim** [comment]
This phase of the abbreviation matching task is now complete.
crefminusbib.txt is an empty file.
4 cases have crept into bibminuscref.txt -- I'll examine these miscreants tomorrow.

100% of the literary source references are matched to pwbib (as extended by pwbib_new.txt).

Hurray!

**Comment by gasyoun** [comment]
Long live the Jim!

**Comment by funderburkjim** [comment]
The 4 miscreants were easily dealt with. Two of them were cases where abbreviations were wrongly added to pwbib_new, when they were already present in pwbib0.

The two other cases required adjustments in abbrv.py, and are a bit more interesting.
 GAN2IT.SPASHT2 (9 cases) and C2A7RN5G.SAM5H.  In these cases pw.txt also shows cases with abbreviations GAN2IT.S (AdityavAra, utkfti) and C2A7RN5G.S (aDogata) .  The current approach treats these three as 'Seite' cases for GAN2IT and C2A7RN5G.   The correction was to adjust the way these Seite cases were recognized by abbrv.py, so that the longer forms GAN2IT.SPASHT2  would not be recognized also as GAN2IT.

They are interesting in that it is possible that the 'S' does NOT represent seite in these three case, but is rather a variant printing of the longer forms;  we can't decide which now.

**Comment by funderburkjim** [comment]
This tapas is now over.  

A good next step will be to prepare materials which will be of help in dealing with the 300 or so 'new' references in pwbib_new.txt.  This will be of help with #56.

It is also possible now to begin thinking how to make use of  this work, first by enhancing the PW display.
