### ISSUE TITLE
digitized PWG bibliography

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/PWK#62]
Thomas Malten recently provided a digitization of the 5 bibliography pages from the PWG  dictionary,
volume 1.

I'm trying to decide where to put this.

One possibility would be to add a `pwg_ls` directory here, in the PWK repository.  The other possibility would be to slightly reorganize the [PWG](https://github.com/sanskrit-lexicon/PWG) repository, and put a `pwg_ls` directory there.

The main reason I'm considering puttting it here (in PWK) is that so doing might facilitate comparisons with PWK bibliography.

I think we should consider doing the same kind of analysis (as in pw_dhaval and pwbib) that we've done with PWK.  

Do others have an opinion regarding where to put this work?

**Comment by drdhaval2785** [comment]
PWG repository.

We can have a uniform decision to keep PWK and PWG repositories in the same
directory (in my case htdocs folder.)

This way we can have relative paths also working well across installations.

**Comment by gasyoun** [comment]
> We can have a uniform decision to keep PWK and PWG repositories in the same
directory

Agree, should be enough.

**Comment by funderburkjim** [comment]
OK Will reorg the PWG repository, and put digitized bibliography there.
