### ISSUE TITLE
displayprep

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/PWK#63]
I'm beginning to work on integrating the PWK bibliographic material into the PW(K) display.

The [displayprep](https://github.com/sanskrit-lexicon/PWK/tree/master/pw_ls/pwbib/displayprep)  directory has this work.

As usual, comments and suggestions are solicited.

**Comment by gasyoun** [comment]
> There is a question about what to do with the volume 0 cases.  
For now, I will just ignore them. 

I would want to see them right from start, Jim.

**Comment by funderburkjim** [comment]
@gasyoun   Per your request, modified things so sortbib has the 'volume 0' cases at the bottom.

These will also be accessible in the display for PWK authorities, 
but they will have no title , since we don't yet know a title.

**Comment by funderburkjim** [comment]
The displays for PW(K) at Cologne have now been modified so that the literary source elements are
links, and bring up a display of the bibliography, similar to that for MW.

This is not yet implemented with the 'apidev' display.

Now is an excellent time for others to examine this enhancement, and look for bugs or other
aspects that need further attention.

**Comment by gasyoun** [comment]
>  source elements are
links

What's the name of the file?

**Comment by funderburkjim** [comment]
> What's the name of the file?

If you use  a display of PW(K) at Cologne, (Basic, List, etc.), you will see that the literary source elements are now hyperlinks.  If you click on one of those, a new 
PWAuthorities display window will pop up, which will be  scrolled to the line for the literary source element.

**Comment by funderburkjim** [comment]
The literary source links now also are functioning in the [apidev list display](http://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/sample/list-0.2.html) for PW.

**Comment by drdhaval2785** [comment]
Now they are tooltips rather than hyperlinks.

**Comment by drdhaval2785** [comment]
The work has been done. Closing this.
