### ISSUE TITLE
<ls> corrections from purenumberabbrvlist

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/PWK#64]
An examination of [purenumberabbrvlist.txt](https://github.com/sanskrit-lexicon/PWK/blob/master/pw_ls/pw_dhaval/abbrvwork/abbrvoutput/purenumberabbrvlist.txt)
shows that there are several (up to 161) items which are present in the file due to digitization errors.

Of these, 89 are matchable to already known literary source abbreviations if they are capitalized,
for example:

```
ra7g4an.10,14.@gaReSakusuma@*gaReSakusuma@34290
```

**Comment by gasyoun** [comment]
Similar in https://github.com/sanskrit-lexicon/PWK/blob/master/pw_ls/pwbib/pwbib_new_work/mergebibnew.txt, just was thinking about the same.

**Comment by drdhaval2785** [comment]
My vague memory says that whenever there are two consecutive references
from one literary source, the dictionary doesn't write the literary source
again. It only writes stanza number. So if we join the Literary sources
just preceding these pure number entries, most of them would be correct.

**Comment by Andhrabharati** [comment]
@funderburkjim 

I presume this issue is now closable.
