### ISSUE TITLE
/pwweb1/web/webtc/

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/PWK#7]
1) Regarding the readme: When you say "Move the 'pw' folder to the 'htdocs' subfolder of your Apache installation." in the readme, you must mean 'pw' = 'pwweb1', right?
2) http://localhost/pwweb1/web/webtc/indexcaller.php
logo links to http://www.sanskrit-lexicon.uni-koeln.de/ instead of http://localhost/pwweb1/web/ - a relevant link will heal it.
3) Corrections  Downloads   Help
links should not be relevant, they should be absolute, otherwise I get http://localhost/php/correction_form.php?dict=PW Object not found!

**Comment by drdhaval2785** [comment]
In 2020, the folder structures have changed. So this question is immaterial. Closing.
