### ISSUE TITLE
PW(K) corrections-1: Andhrabharati

### ISSUE THREAD

**Issue by Andhrabharati** [sanskrit-lexicon/PWK#72]
[As I have never left a work (to the planned level) unfinished, this is just an indication that my PWG session is over; was thinking of proofing the HWs portions as some errors were noticed during my work. May be sometime very soon.]

It is but natural that one would see PWK after PWG (**when seriously interested**).

I have the PWK text converted into Devanagari, and the very first corrections list is being posted here.

![PW(K) corrections-1](https://user-images.githubusercontent.com/75209130/128160881-99091e56-1e95-4ac0-bfc8-e1c50fcc168e.png)

[This is with a check for "small letter followed by Cap. letter". **Similar correction was done in PWG in my working.**]

**Comment by funderburkjim** [comment]
@Andhrabharati Will get to this eventually.

**Comment by gasyoun** [comment]
> was thinking of proofing the HWs portions

@Andhrabharati please, please, please.

**Comment by drdhaval2785** [comment]
Any update @Andhrabharati ?

**Comment by Andhrabharati** [comment]
> 
> 
> Any update @Andhrabharati ?

???

**Comment by Andhrabharati** [comment]
I think, this issue is closeable now.
