### ISSUE TITLE
PW(K) corrections-2: Andhrabharati

### ISSUE THREAD

**Issue by Andhrabharati** [sanskrit-lexicon/PWK#73]
It is seen that extra space is inserted into the text at all the citation numbers (between commas and fullstops) in Cologne's PWG digitisation (and is still remaining as such there), and all the spaces at such places are removed in Cologne's PWK digitisation (esp. between the ls word groups and the citation numbers).

Wonder why such a different action has taken place in the two **closely related** works; probably @thomasincambodia can throw some light on this.

**Comment by Andhrabharati** [comment]
@funderburkjim,

Pl. look at the ~30 places having _ in the Devanagari text (k2 field).

Many of them are words with a space in between (I recall you were saying no provision to have such entries as having spaces in your digitisation, while we were discussing on the MW work); and some are with a vowel in the 2nd word beginning (all such vowel+vowel are combined in the SLP1 notation but are proper in k2 field) and some with a consonant [search for prAGAra- this has prAg_hAra & the actual prAGAra clubbed together!!].

**Hope you'd like to correct these _ places, as appropriate.**

**Comment by gasyoun** [comment]
> vowel+vowel are combined in the SLP1 notation but are proper in k2 field

This is the only case where HK would fail.

> why such a different action has taken place in the two closely related works

Does not makes sense to me.
