### ISSUE TITLE
muhUrtawIkA  multiple entries

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/PWK#78]
In making the correction to muhUrtasaMgraha (see #72),  noticed that this word occurs in entry L=87785, muhUrtawIkA,
and that this entry is composed of a list of several 'titles of works',  the first one being muhUrtawIkA.  

Believe it would be useful to decompose this L=87785 into several entries, one for each of the works mentioned.

Does anyone have an opinion on this suggestion?

![image](https://user-images.githubusercontent.com/6393033/138793989-be49432f-0139-434d-aa27-5015a2e4a3be.png)

**Comment by Andhrabharati** [comment]
@funderburkjim,

Now that we've finished the task of alt. HW markup, this issue could be closed now. Isn't it?
