### ISSUE TITLE
help.html Help Page

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/PWK#8]
1) <a href="http://www.sanskrit-lexicon.uni-koeln.de/scans/PWScan/2014/web/webtc/help.html">Help for Sanskrit-Wörterbuch in kürzerer Fassung</a> lacks at least a few examples of entries. Please consider. Why not add:
Devanagari: अऋणिन्
IAST: aṛṇin
HK: aRNin
SLP1: afRin
ITRANS: aRiNin
2) "Help" - the name of the section itself makes me feel strange. I never know what I will get after clicking on it, but actually it's the Transliteration and Accent section. Transliteration scheme is for input (so should be close to "citation:" box), Accent is for output, reading the text. I would move the general Help around the "citation" input box, rename Help to Accents - then it would make more sense. Or have it in two places. Shalu, agree, no?

**Comment by drdhaval2785** [comment]
Now the transliteration and accents are two pages indeed. 
https://www.sanskrit-lexicon.uni-koeln.de/scans/PWScan/2020/web/webtc/help.html and https://www.sanskrit-lexicon.uni-koeln.de/scans/PWScan/2020/web/webtc1/help/accents.html respectively. Closing.
