### ISSUE TITLE
MBH Calcutta edition links in PWK

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/PWK#82]
While most of the ls links to Mahabharata in PWK are to the Bombay edition, there are several to the Calcutta edition.  See [this comment in issue 48](https://github.com/sanskrit-lexicon/PWG/issues/48#issuecomment-1024830811).

The aim is to 
* reexamine the MBH ls references in pwk, and improve markup where needed so that links to
   calcutta edition may be identified in the display programs.
* modify the display programs  in csl-websanlexicon repository so the Calc. ed. links will be active

**Comment by gasyoun** [comment]
> to the Bombay edition

@Andhrabharati what to we know about it?

**Comment by Andhrabharati** [comment]
did not get what you want to say/ask!

**Comment by gasyoun** [comment]
![mbh missing](https://user-images.githubusercontent.com/80761/165398872-4fb3bc74-e52b-4f49-83c7-d7d6899f8b8e.png)

@funderburkjim do you understand why it's broken?

**Comment by gasyoun** [comment]
@Andhrabharati 
I mean how many scans of Bombay or Calcutta edition you are aware of?

![ddssdadsddsadsa](https://github.com/user-attachments/assets/30e4ce63-4e43-4972-b6a2-bed44dd56e8a)

This is a page from a miserable scan of Calcutta edition at Google. Where is the best one?

Mahābhārata, Calcutta ed., 1834—1839 - is there an OCR?

**Comment by Andhrabharati** [comment]
> I mean how many scans of Bombay or Calcutta edition you are aware of?

This would not get any answer from me, @gasyoun!
[You should come up with a more specific (and particular) query; how does knowing the number of various editions that I know (or have) matter to you? But, you may refer to the earlier posts by me, when the MBh. project was "under progress". And I have recently given the links for the Bombay ed. MBh. that PWG has used, with which you were to take up some work.]

> This is a page from a miserable scan of Calcutta edition at Google. Where is the best one?

This indicates what I repeatedly say, that you forget things very fast!
Were you not using the CDSL MBh. (Calcutta ed.) links so far, which is the very first one (and by all means, "the most widely used" target) in the mega-project of linking the PDFs took up by Jim (on my proposal)?

> Mahābhārata, Calcutta ed., 1834—1839 - is there an OCR?

Not with anyone, that I know of! [Of course, I do have a prelim. version (but won't share with you); why don't you get it done by Martin et al.? ]

**Comment by gasyoun** [comment]
> You should come up with a more specific (and particular) query; how does knowing the number of various editions that I know (or have) matter to you?

I'm asking you to share your knowledge. Because a knowledge unshared and unused is a burden. Sometimes too heavy.

> But, you may refer to the earlier posts by me, when the MBh. project was "under progress".

I tried to find them, before I asked, but failed.

> And I have recently given the links for the Bombay ed. MBh.

I have asked not about Bombay, but about Calcutta, because the first Russian translation was made from Calcutta translation. I need it to add 24 000 shlokas, including Mokshadharma in way I have done for the critical edition https://samskrtam.ru/parallel-corpus/mahabharata.html

> This indicates what I repeatedly say, that you forget things very fast!

Indeed, you are right. 

> Were you not using the CDSL MBh. (Calcutta ed.) links so far, which is the very first one (and by all means, "the most widely used" target) in the mega-project of linking the PDFs took up by Jim (on my proposal)?

I was, but knowing how to find a link target and knowing where the scans and OCR are, is not the same.

> why don't you get it done by Martin et al.

Martin is at the five volume CESS https://planeta.ru/campaigns/cess2. Everyhting he does is open. Seems to be that not so with you. 

> I do have a prelim. version (but won't share with you)

I tried to use chatGPT for that but it worked only for a page. I see that you want to play, not work, and nothing in this world can change your mind, I believe. Too bad we are waisting or days, doing the same work over and over again in the field of Indology.

**Comment by gasyoun** [comment]
> Is it the Skt. original or the English translation of the Cal. ed., that you are looking for?

Would love to see the English translation as well. But I was looking for the original.

Page 727 in Mokshadharma is spoiled. What would be a good source to replace it with?

![photo_2024-11-06_20-16-03](https://github.com/user-attachments/assets/a977da50-77d3-4cfe-8da3-dca2d43096d9)

> Now that earlier Bavarian library link is not giving any downloads (as I see), but all those collections are accessible through another link.

Right.

> You cannot image how much time I spend at my Work, on widely varying topics/areas.

Not only I can, but do. You are like a factory, like a whole Indology institute. But if your work can help others in the field, why should you try to hide it any longer?

**Comment by Andhrabharati** [comment]
> Page 727 in Mokshadharma is spoiled. What would be a good source to replace it with?

https://github.com/sanskrit-lexicon-scans/mbhcalc/blob/main/pdfpages/mbhcalc_3.727.pdf

https://www.digitale-sammlungen.de/en/view/bsb10219683?q=Mahabharata&page=733

**Comment by funderburkjim** [comment]
The problem @gasyoun mentioned above at [do you understand why it's broken?](https://github.com/sanskrit-lexicon/PWK/issues/82#issuecomment-1110288298) is no longer a problem (the link works).

Since I opened this issue,  it seems closeable now. So am closing.

**Comment by gasyoun** [comment]
What need of index.html in the URL? @funderburkjim 
https://sanskrit-lexicon-scans.github.io/mbhcalc/?13.1729 works short.

Why should be longer? Length of links matters. Especially when you send it.
https://sanskrit-lexicon-scans.github.io/manu/index.html?9,321 
https://sanskrit-lexicon-scans.github.io/kss/index.html?20,216
