### ISSUE TITLE
pw literary source summary

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/PWK#85]
Per requests at https://github.com/sanskrit-lexicon/PWG/issues/51,
a summary for PW(K) of the `<ls>` markup has been made.

**Comment by funderburkjim** [comment]
See [lsextract_pw.txt](https://github.com/sanskrit-lexicon/PWK/blob/master/pw_ls/summary/lsextract_pw.txt)

**Comment by drdhaval2785** [comment]
This does not require further work. If someone gets full form of a literary source, it can of course be corrected. Maybe in separate issue.
