### ISSUE TITLE
Small error in "[Page...]" marking

### ISSUE THREAD

**Issue by Andhrabharati** [sanskrit-lexicon/PWK#89]
Though not any critical, just seen these-

Missing 0 (after vol. number):
> [Page384-2]
> [Page385-1]
> [Page385-3]
> [Page387-3]
> [Page423-1]
> [Page484-2]
> [Page495-2]
> [Page567-2]
> [Page599-1]
> [Page750-1]
> [Page754-3]
 
 Extra 0 (after vol. number):
> [Page40152-3]

@funderburkjim might wish to correct these to bring them in line with others.

**Comment by funderburkjim** [comment]
These errors corrected.

**Comment by funderburkjim** [comment]
@Andhrabharati @drdhaval2785 @gasyoun 

Dhaval recently noticed that the sanskrit-lexicon organization has been 'flagged' by Github.  I have sent a request to Github support to request this to be removed.

One side-effect of being flagged is that, if you click on 'issues',  you see that '0 are open and 0 are closed -- in other words there is no way to search the issues!

The ability to push and pull repositories seems to be normal.

Hopefully the issue comments (such as this comment) will continue to be visible to others, until this 'flagging' problem is resolved.

**Comment by Andhrabharati** [comment]
> These errors corrected.

I still see these in the pw.txt at /csl-orig/v02/...; where is the corrected file @funderburkjim ?

**Comment by funderburkjim** [comment]
@Andhrabharati Here is link to the commit where these corrections were made:
https://github.com/sanskrit-lexicon/csl-orig/commit/2cf2608d2b5e3a5b5d6624982e65960cfef36c33

**Comment by gasyoun** [comment]
> Dhaval recently noticed that the sanskrit-lexicon organization has been 'flagged' by Github. I have sent a request to Github support to request this to be removed.

Me yet to do it. Finally I was able to log in!

> One side-effect of being flagged is that, if you click on 'issues', you see that '0 are open and 0 are closed -- in other words there is no way to search the issues!

And not only that.

![404](https://user-images.githubusercontent.com/80761/174172039-29cf9a17-cd46-4e48-bdf9-225600346c6e.jpg)

Links from dictionaries not working as well.

**Comment by funderburkjim** [comment]
Last week, opened a ticket to Github support requesting the sanskrit-lexicon flag be removed.
Today received this response from Github support:

> Hi Jim,
Thanks for writing in about this. Sometimes our abuse-detecting systems highlight accounts that need to be manually reviewed.
We've cleared the restrictions from the account, so it should be back to normal now.

And, things do appear to be back to normal now.

**Comment by gasyoun** [comment]
>  appear to be back to normal now

Thanks, @funderburkjim. Wonder what falsely triggered the abusre detector.

**Comment by Andhrabharati** [comment]
Corrections incorporated, so closing the issue now.

**Comment by funderburkjim** [comment]
> Wonder what falsely triggered the abusre detector.

So do I wonder.  The comments from Github support provided no indication of the trigger.
