### ISSUE TITLE
Gorresio Ramayana links

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/PWK#90]
Improvement of markup and display for Gorresio Ramayana in pwk.

There are 120 instances of 'GORR' in pw.txt. Within `<ls>` tags, these have one of three 
forms:
`<ls>R. GORR.`, `<ls>R. ed. GORR.`  and `<ls>GORR.`.  

basicdisplay.php (in csl-apidev repository and in csl-websanlexicon repository)  is adjusted to recognize all three forms for pwk (or pwg). 

When one of these is followed by 3 numbers,  the displays now generate a link to a scanned image, for instance https://sanskrit-lexicon-scans.github.io/ramayanagorr/?2,105,43.

In pw.txt, there are a few cases where multiple references occur, such as `<ls>R. GORR. 2,62,2. 95,16.</ls>`.  These are adjusted so links are provided for each references.
e.g. `<ls>R. GORR. 2,62,2.</ls> <ls n="R. GORR. 2,">95,16.</ls>`

**Comment by funderburkjim** [comment]
## R. multiple links.
Similarly added markup for multiple "R." links: Example
```
OLD:
<ls>R. 4,7,2. 6,106,11.</ls>
NEW: 
 <ls>R. 4,7,2.</ls> <ls n="R.">6,106,11.</ls>
```

[change_1.txt](https://github.com/sanskrit-lexicon/PWK/blob/master/pw_ls/gorr/change_1.txt) and [change_2.txt](https://github.com/sanskrit-lexicon/PWK/blob/master/pw_ls/gorr/change_2.txt) have the changes  for 'GORR' (12) and 'R' (18), respectively.

**Comment by funderburkjim** [comment]
## R. x,y,z etc

According to [pwbib_input.txt](https://github.com/sanskrit-lexicon/csl-pywork/blob/master/v02/distinctfiles/pw/pywork/pwauth/pwbib_input.txt), we think the "R." abbreviation should refer to the Schlegel edition:

> RĀMĀYAṆA. Das 1ste und 2te Kāṇḍa nach der Ausg. von SCHLEGEL, das 3--6te nach der von GORRESIO, das 7te nach der Bomb. Ausg., wenn nicht ausdrücklich eine andere Ausgabe genannt ist. Eine eingeklammerte Zahl bezieht ist sich auf ed. Bomb. 

> (English via Google Translate) The 1st and 2nd Kāṇḍa after the output of SCHLEGEL, the 3rd--6th after that of GORRESIO, the 7th after the bomb. Edition unless another edition is explicitly mentioned. A number in parentheses refers to ed. Bomb.

Yet there are such R. references for verses in Kanda's 3 and following, such as 
`<ls>R. 4,7,2. 6,106,11.</ls>` under headword anugrAhya.

(In fact there are 440+ matches to `<ls>R. [3-7]` in digitization pw.txt.)

A link to https://sanskrit-lexicon-scans.github.io/ramayanaschl/?4,7,2  leads nowhere.
https://sanskrit-lexicon-scans.github.io/ramayanagorr/?4,7,2 leads somewhere, but the verse does not use the word anugrAhya.

Similarly,  link to https://sanskrit-lexicon-scans.github.io/ramayanaschl/?6,106,11 leads nowhere.

BUT https://sanskrit-lexicon-scans.github.io/ramayanagorr/?6,106,11 leads to a verse which DOES use the word anugrAhya !

Thus the 'R.' references in PW remain puzzling.

AFAIK, we have no link target for the 'Bombay edition'  of Ramayana.

**Comment by Andhrabharati** [comment]
Surprising, @funderburkjim that in spite of looking at the translated text about R. abbreviation
> (English via Google Translate) The 1st and 2nd Kāṇḍa after the output of SCHLEGEL, the 3rd--6th after that of GORRESIO, the 7th after the bomb. Edition unless another edition is explicitly mentioned. A number in parentheses refers to ed. Bomb.

you are saying 
> Thus the 'R.' references in PW remain puzzling.

All R. citations having the Kandas 3-6 refer to Gorresio; and all citations having Kanda 7 (most probably) refer to Bombay ed. (Need to see if the Gorresio's vol. 7 too has them all).

As seen in my file, there are 43 occurrences of `<ls>R.</ls> <ln>7` in pwk.txt, and atleast 50 places where a v.l. form is cited to be from it as `<ls>ed. Bomb.</ls> <ln>`.

Do you want the link target for this Bombay ed. of Ramayana?

**Comment by gasyoun** [comment]
> All R. citations having the Kandas 3-6 refer to Gorresio; and all citations having Kanda 7 (most probably) refer to Bombay ed. (Need to see if the Gorresio's vol. 7 too has them all).

So not sure yourself, right?
