### ISSUE TITLE
remove sanskrit italics 

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/PWK#91]
Solve the problem mentioned in https://github.com/sanskrit-lexicon/csl-orig/issues/1033.

**Comment by funderburkjim** [comment]
Get latest version of this pwk repository from github:
* If you already have local version of pwk repository, do a git pull
* Otherwise (or alternatively), `git clone X` where X is here:
   * 
![image](https://user-images.githubusercontent.com/6393033/209492515-df9495c3-6f3c-48fc-83f3-6a38ab458dbd.png)

**Comment by funderburkjim** [comment]
Similarly, get  up-to-date local installation of sanskrit-lexicon/csl-orig  repository.

**Comment by funderburkjim** [comment]
@AnnaRybakovaT   I have prepared a 'sample'  for the change.  It just changes 'Pron.' to 'Pronoun' 
Files are in the pwk/pwsissues/issue91 folder.
Once you are set up as above, try
```
python change_sample.py temp_pw_0.txt tempanna_change_sample.txt
# then
diff change_sample.txt tempanna_change_sample.txt
# there should be no output  (meaning the files are the same)
```

At this point, make a copy:
```
cp change_sample.py change_1.py
```

Then modify the change_1.py to do what we really want to do here.
```
python change_1.py temp_pw_0.txt change_1.txt
```

When done,  modify readme.txt to say what was done.
Then push the revised pwk repository.

Good luck!

**Comment by AnnaRybakovaT** [comment]
> python change_sample.py temp_pw_0.txt tempanna_change_sample.txt

Dear Jim,
I have some difficulties on this step:
```
Rybakova@ST-Rybakova MINGW64 ~/Documents/sanskrit-lexicon/PWK/pwkissues/issue91 (master)
$ python change_sample.py temp_pw_0.txt tempanna_change_sample.txt
Traceback (most recent call last):
  File "change_sample.py", line 100, in <module>
    entries = digentry.init(filein)
  File "C:\Users\Rybakova\Documents\sanskrit-lexicon\PWK\pwkissues\issue91\digentry.py", line 30, in init
    with codecs.open(filein,encoding='utf-8',mode='r') as f:
  File "C:\Users\Rybakova\AppData\Local\Programs\Python\Python38\lib\codecs.py", line 905, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: 'temp_pw_0.txt'

```

**Comment by AnnaRybakovaT** [comment]
> temp_pw_0.txt

And I can't understand what is this file.

**Comment by funderburkjim** [comment]
@AnnaRybakovaT  I got a notification of an email from you from this issue, part of which said that
that you got an error when trying
`python change_sample.py temp_pw_0.txt tempanna_change_sample.txt`
because the file temp_pw_01.txt was not found.

Looks like I forgot to say something.

Here's what to do:
* locate your copy of csl-orig/v02/pw/pw.txt
* copy that file to your copy of pwk/pwissues/issue91/ and rename to temp_pw_01.txt

**Comment by funderburkjim** [comment]
Oops. I goofed again.
Abvoe, I should have said
`copy that file to your copy of pwk/pwkissues/issue91/temp_pw_0.txt`  

I think my comments in readme.txt of issue91 directory are correct regarding temp_pw_0.txt.

I did make one change in readme.txt in pwk/pwkissues/issue91,  So please pull pwk again first.

Jim

**Comment by AnnaRybakovaT** [comment]
> I got a notification of an email from you from this issue, part of which said that
> that you got an error when trying

Dear Jim, Yes, in the beginning I had this problem but after reading the readme.txt (better to do it always first of all) it was solved.

**Comment by AnnaRybakovaT** [comment]
So, I need help. After long pause I was trying to refresh my knowledge but it was not enough. 
There is my logical chain:
1) there is a correction which has to be done 
old: <div n="1">— 1) {%erfreuen. {#anumodita#} erfreut.%}
new: <div n="1">— 1) {%erfreuen.%} {#anumodita#} {%erfreut.%}

2) for identification of  lines with italic Devanagari we can use regular expressions and metacharacters. 
For searching you have used this expression:
"{%[^%]+{#"
Could you explain me  each symbol, please?
As I see there are two conditions {%[^% and {#. 
I can't understand this symbol at all "[". 
As I know symbol "^" = starts with

3) Is it possible to generate changes just by line.replace or re.sub (if by metacharacters we will explain where and how exactly we wanna to make changes)?

**Comment by funderburkjim** [comment]
OK. This is a question of how to do string replacements with the 're'  (regular expression) module of Python.  

Regular expressions can be quite complicated, and our current task is moderately
advanced.  Lets use the current task as motivation for your becoming self-sufficiant with regular expressions in general, and more specifically in Python.

I assume you know the basics of regular expressions and how to use 
re.search, re.sub, re.findall in Python?  
Many on-line resources for beginning tutorials on Python regular expressions.
For example, https://www.w3schools.com/python/python_regex.asp .

In a regular expression *pattern*, *usually* `[X]` matches a set of characters
For example, `[dh]` is a set of two specifiic characters.

X can also be written to match a range of characters: `[b-f]` matches  5 characters.
And there are a few other details regarding how X is interpreted.

The `^` character does usually mean 'starts with' in a regular expression pattern.
However, `^` has a different meaning when it is the first character in a pattern representing a set of characters.  i.e., 
`[^X]`  matches any set of characters *except* those in X.
So `[^dh]`  matches any characters except 'd' and 'h'.
and `[^%]` matches any character except '%'.

Symbolically, we can represent our task approximately as
`{%X{#Y#}Z%} -> {%X%}{#Y#}{%Z%}`

When you're ready, we'll think together further about our task. Questions always welcome at any point.

**Comment by AnnaRybakovaT** [comment]
> {%X{#Y#}Z%} -> {%X%}{#Y#}{%Z%}

Dear Jim,
Thank you very much for explanations. I realised my missunderstanding redarding set of characters [ ].
If I wanna to use re.search, I know what exactly we would like to replace
{%X{#Y#}Z%}  -> \{%[^%]+\{#.+#\}
but I have problems with the second component
{%X%}{#Y#}{%Z%}  -> ?

newline = re.sub(r'\{%[^%]+\{#.+#\}', '?', line)

In the beggining I wanted to use one more regular expression (something like this):
? ->  \{%.%\}+\{#.+#\}\{%
but it doesn't work

Could you kindly give me some advices?

**Comment by funderburkjim** [comment]
A name for the 2nd argument of re.sub (the one you call '?') seems to be the *repl* argument.
A name for the 1st argument might be the 'match pattern' or just the *pattern* argument.
A near solution to our problem can be found by using two features:
* `()	Capture and group` in the pattern to identify X, Y, and Z
* back-reference in the  repl argument of re.sub 
  
Suppose we wanted to change 'pXt'  to 'bXt' in any string, where X is a vowel.
So pit -> bit, pat -> bat, etc.
```python
import re
pattern = 'p([aeiou])t'
repl = r'b\1t'   # r means 'raw' string  See note below
old = 'Please pet the dog'
new = re.sub(pattern,repl,old)
print(new)  # Please bet the dog
```
The '\1' in repl refers to the first matching group in pattern.
In our example there is only one matching group.
So what is the reason for the `r` in repl?
Try the example without the 'r'.  You will see that the vowel is not properly
represented in 'new'.  The reason is that 'repl is a Python string, and in a python string the backslash normally has a special meaning. For instance `'\t'` represents the tab character.   But in our 'repl' string, we want to turn off this special meaning.
For instance `r'\t'`  would represent a 2-character string.
This r'X' syntax is referred to as a "raw string" in Python.

Try to apply this information to our situation. I think the solution should be ALMOST right.

**Comment by funderburkjim** [comment]
Try to get pattern and repl to change 
```
'blah {%heavy {#guru#} teacher%}'
```

**Comment by AnnaRybakovaT** [comment]
> 'blah {%heavy {#guru#} teacher%}'

Dear Jim,
Please, check this solution:
```
import re
old = 'blah {%heavy {#guru#} teacher%}'
x = re.findall(r'{%[^%]+{#.+#}', old)
if (x):
  old1 = old
  pattern = '({#.+#})'
  repl = r'%} \1 {%' 
  new = re.sub(pattern,repl,old1)
  print(new) #  blah {%heavy %} {#guru#} {% teacher%}
```
In general it works. BUT I need your help with our python file.
Could you explain where I am wrong:
```
def make_changes(entries):
 n = 0
 for entry in entries:
  changes = []
  for iline,line in enumerate(entry.datalines):
   x = re.findall(r'{%[^%]+{#.+#}', line)
   if (x):
    line1 = line
    pattern = '({#.+#})'
    repl = r'%} \1 {%'
    newline = re.sub(pattern,repl,line1)
    if newline == line:
     continue
     change = Change(iline,newline)
     entry.changes = changes


$ python change_1.py temp_pw_0.txt change_1.txt
  File "change_1.py", line 28
    newline = re.sub(pattern,repl,line1)
                                      ^
IndentationError: unindent does not match any outer indentation level

```

**Comment by funderburkjim** [comment]
Please add/push  -- I'll need to see the file.

**Comment by funderburkjim** [comment]
I should have said 'add/commit/push' . You might also do a 'git status' after 'add', to check that you are committing only what you intend to commit.

**Comment by AnnaRybakovaT** [comment]
> I'll need to see the file

Dear Jim,
Now you can see the file change1.py

**Comment by funderburkjim** [comment]
@AnnaRybakovaT  You have tab characters in lines 25,26,27.  Maybe your text editor did this, maybe you did it on purpose.  Either way, bad idea.  That is what caused the IndentationError message which means things did not 'line up' properly.

Recommend you follow the 'one-space' indentation method that I use 
in this file and other code files.  Go ahead and make this change, so at least your change_1.py program runs.

When you get past the indentation problem, there will likely still be some problems with your code, although I'm not sure how the problems will manifest themselves.   Struggle a bit with a solution.  Do a few exercises on re.findall, re.sub, re.search  such as at that w3schools link, and perhaps some other online resource that you find.  

When you're more comfortable with what these re functions do,  come back to our problem.  

You might try to learn how to do small code tests, where the problem area is isolated from its current rather complex environment within change_1.py.  

When you're ready,  upload further test code and/or new change_1.py  and describe where stuck in a comment here.

**Comment by funderburkjim** [comment]
In your test programs,  use a function 'change_line(old)' to do the work.  It will return 'new'.
Both old and new are strings.   If the line does not have the pattern, the returned 'new' will be the same as 'old'.

You can try out different inputs for 'old'  in your test program, and the 'main' part of the test program will print out old and new.

When the change_line function works in your tests, then you can copy it into change_1.py, and then
make_changes function will say `newline = change_line(line); if newline=line:continue, else .....`

**Comment by AnnaRybakovaT** [comment]
> at least your change_1.py program runs

Dear Jim,
I have corrected lines 25-27, but still my rogram doesn't run:
```
$ python change_1.py temp_pw_0.txt change_1.txt
682619 lines read from temp_pw_0.txt
135788 entries found
Traceback (most recent call last):
  File "change_1.py", line 109, in <module>
    write_changes(fileout,entries)
  File "change_1.py", line 45, in write_changes
    nchange = nchange + len(entry.changes)
AttributeError: 'Entry' object has no attribute 'changes'
```

**Comment by AnnaRybakovaT** [comment]
> You might try to learn how to do small code tests,

I will try to do it on Monday.
Just now I would like to congratulate you with New year! My the best wishes!!!!!!!!

**Comment by funderburkjim** [comment]
The error is due to an indentation problem at line 38 - that is where 'entry.changes' is set.
There are also a couple of other indentation problems.

I have corrected these in file change_1_ejf_01.py.  
1. modify your  change_1.py similarly
  * then change_1.py should run. 
2. modify readme.txt to show how you run change_1.py

Happy New Year to you as well! -- Maybe the new year has already started in your time zone?

**Comment by AnnaRybakovaT** [comment]
> Maybe the new year has already started in your time zone?

Dear Jim, 
Thanks for your congratulations! In Greece the new year started in some hours after I had sent this message. I had enough time to make dinner since we celebrated at home.

**Comment by AnnaRybakovaT** [comment]
> You might try to learn how to do small code tests

To check if my regEx functions work, I have written the python program test1.py (by updating our the first python program readwrite.py). test1.py reads the lines of test.txt and write all lines (including updated lines) to the file results1.txt

**Comment by AnnaRybakovaT** [comment]
> When the change_line function works in your tests, then you can copy it into change_1.py, and then
> make_changes function will say `newline = change_line(line); if newline=line:continue, else .....`

But I have problems on this step. After a hour of unsuccessful tests I need your help. Please check the file change2.py

**Comment by AnnaRybakovaT** [comment]
> problem at line 38

Thanks! I tried to be attentive, but I missed this error.

**Comment by funderburkjim** [comment]
## love the comments 
Really nice comments  in test1.py.  
They are a big help in knowing your thoughts.
Also, the organization of '__main__' is excellent.

I have made a new version, which simplifies 'change_lines' so all the work of changing one line
is done in a separate change_one_line function

## test2.py
This is a refactoring of test1.py.  
Reason: To make it easier to debug how we handle each line of input.
Note the comments added to readme.txt. 

## Not sure about findall
in change_one_line, temporarily print out 'x', which is returned by re.findall.
Is x ever None?  Is this what you expected?  Is 'x' ever used otherwise? Is re.findall needed at all?

## test3.py
Ponder the logic of change_one_line.  Make a new version, test3.py.  And experiment some with
change_one_line.  Continue the good documentation comments
in revised change_one_line of test3.py,  and be sure to add usage comments to readme.txt.
When you're done (or stuck)  add/commit/push. 
NOTE:  In your commit message, add '#91' --  Do you see what this does in the comments of this issue?



In this case,  we still have problems to solve

**Comment by funderburkjim** [comment]
Note:  That `temporarily print out 'x'` comment should be done in test3.py.  Leave test1 and test2 as they are.

**Comment by funderburkjim** [comment]
Comment on change_test.py.

Your 'change_line' function in change_test is 'grammatically correct'  (properly indented, etc.) .  

There are several problems in make_changes function. The program fails with error:
```
  File "C:\xampp\htdocs\sanskrit-lexicon\PWK\pwkissues\issue91\change_test.py",
line 31, in make_changes
    newline = change_line(line)
NameError: name 'line' is not defined
```

This is because change_test is missing the  loop over entry.datalines:
`for iline,line in enumerate...` of change_1.py


When you get change_test to work, 
Let's continue work with test3, etc.

When test99.py 😄 is working properly, then  we will be ready to go back and replace 'change_line' with  perfected 'change_one_line' function.

DEBUGGING gets complicated, and somewhat hard to discuss.  Persevere!

**Comment by AnnaRybakovaT** [comment]
> Note: That `temporarily print out 'x'` comment should be done in test3.py. Leave test1 and test2 as they are.

Dear Jim,
please, see the file test3.py
As you mentioned before re.findall was not necessary function.
To be honest from the beginning I wanted to use a pattern from two groups but since I am not so confident in syntaxis, probably I did some mistackes in some symbols. Since I couldn't find this solution I started to find other options, where re.findall and re.search were on of them.

**Comment by AnnaRybakovaT** [comment]
> This is because change_test is missing the loop over entry.datalines: `for iline,line in enumerate...` of change_1.py
> 
> When you get change_test to work,

Thank you, now I can run the program but still without results - this program can't make changes. I did some tests unfortunately the same result.

**Comment by AnnaRybakovaT** [comment]
> Do you see what this does in the comments of this issue?

Yes, I see))

**Comment by AnnaRybakovaT** [comment]
> Really nice comments in test1.py.

Of cource all comments are nice since they belong to you (I have just usedalmost all your comments fro the 1st python program). 
Sorry, I do not want to upset you, but my skills are not so high yet.

**Comment by AnnaRybakovaT** [comment]
> Note the comments added to readme.txt.

Dear Jim,
I wanted to compare result1.txt and result2.txt by the 'diff' utility (how it mentioned in the readme.txt).  There are NO differences between and nothing was printed to terminal. As well I did test for two more files which sure have differences between but NOTHING was printed to terminal.
I just wanna to see what I do wrong:
```
Rybakova@ST-Rybakova MINGW64 ~/Documents/sanskrit-lexicon/PWK/pwkissues/issue91 (master)
$ git diff result2.txt readme.txt
```

**Comment by funderburkjim** [comment]
> Of cource all comments are nice since they belong to you

This made me laugh., as I didn't recognize these comments as coming from me.  Usually my comments are not so good.

**Comment by funderburkjim** [comment]
> git diff result2.txt readme.txt

not `git diff file1 file2`
use `diff file1 file2`

`diff result2.txt readme.txt` will give lots of output, since these two files are completely different.

`diff result1.txt result2.txt`  will give no output, since these two files are identical.

## what about git diff?

The 'git' program DOES have a 'diff' option  (sort of like 'git add' runs the 'add' option of git).  As with all git option the diff option of git has many variations (which can be seen by google search on 'git diff').  The only variation I understand and use (but only occasionally) is 
`git diff FILENAME`  (one argument FILENAME).

Here is a description of when 'git diff FILENAME' might be useful.
Suppose you make a small change to change_1.py (or result1.txt, any file tracked by git).
When you do a 'git status',  this changed file will be listed as modified.
But you forgot what change you made to the file.  So the file is (a) modified but (b) not yet commited.   How can you find out exactly what was changed in that file?
Answer : `git diff FILENAME`.  

Next comment will walk through an example of `git diff FILENAME`

**Comment by funderburkjim** [comment]
## make a change to result1.txt and see how this is noticed by `git status`

![image](https://user-images.githubusercontent.com/6393033/210407886-1b9faa2f-1ac6-4194-894c-fe0500471bef.png)

## I forgot what was changed.  Use 'git diff` to find out

![image](https://user-images.githubusercontent.com/6393033/210408547-c4c054a6-86b8-4b09-a584-dada21a6143e.png)

## Bonus 'git restore'
I really didn't want to make those changes to result1.txt.  'git restore' to the rescue to undo the changes.  Notice that in the last 'git status',  there was this helpful comment
`(use "git restore <file>..." to discard changes in working directory)`

![image](https://user-images.githubusercontent.com/6393033/210409278-5e8bef89-09a0-4c4e-82f0-b6f5d07ef4dd.png)

**Comment by funderburkjim** [comment]
## test3 

change_one_line is close to the desired.

## test4
I found it awkward to compare individual lines of test1.txt with those of result3.txt.
test4.py revises write_lines, so as to make the comparison easier.
@AnnaRybakovaT Study write_lines in test4.py  (and the minor change to 'main').
I tried to do 'good commenting'. Also wrote usage note in readme.

## result4
* The 'SAME' lines 2 and 6 are as desired.
* The 'SAME' line 5 I am unsure about, but
   * I think it should also be changed, despite the 'naked' % sign
   * But HOW to accomplish that might require a new technique
* The 'DIFFERENT' lines (1,3 and 4) are ALMOST as desired.
   * the only problem is with space characters
   * I think the solution might also require that new technique.

Next steps for you, @AnnaRybakovaT .
* Spend time studying test4.py, and raise any questions as needed.
* The 'new technique' is, succinctly, to use a FUNCTION in 'repl' !
   Do some preliminary study as indicated below.
 
## learning how to use a function for 'repl' 
`newstring =  re.sub(pattern, FUNCTION, string)`  This is the form.

This technique is considered advanced, and I haven't found a good thorough explanation.
Here are some preliminary web resources to get you started.
* https://pynative.com/python-regex-replace-re-sub/    
  * The section titled *Regex replacement function*
* https://stackoverflow.com/questions/18737863/passing-a-function-to-re-sub-in-python
  * The section titled *A solution without lambda*
* https://www.pythontutorial.net/python-regex/python-regex-sub/
  * The section *4) Using the regex sub() function with the replacement as a function*
 
Using a string with backreferences (e.g. '\1' for repl) is not quite flexible enough in our
situation. Using a function for repl provides enormous flexibility. 
In our case, we might take pattern as all italic texts:  `{%.*?%}`  [Do you understand the '?'].
Then `re.sub(pattern, replfunc,line) would start with each italic substring in line, do some changes to that italic substring as required, return the replacement for the italic substring,
and, and then re.sub would replace the italic substring with that replacement.

So, anyway, get started with this using the examples sources given above.  
When you're ready, I'll contribute further suggestions.

**Comment by AnnaRybakovaT** [comment]
> Bonus 'git restore'

Thanks! It works))))!

**Comment by AnnaRybakovaT** [comment]
> not `git diff file1 file2` use `diff file1 file2`
> 
> `diff result2.txt readme.txt` will give lots of output, since these two files are completely different.

Thank you very much!

**Comment by AnnaRybakovaT** [comment]
> Study write_lines in test4.py (and the minor change to 'main').
> I tried to do 'good commenting'. Also wrote usage note in readme.

Dear Jim,
Everything is more that clear (thanks to your nice comments)!
Tomorrow I will focus on replacement function.

**Comment by AnnaRybakovaT** [comment]
> {%.*?%}

Dear Jim, 
The given above sources are really useful and informative. Many thanks!

Unfortunately I still can't find solution for current task. There are just some ideas:
```
line = '1) {%erfreuen. {#anumodita#} erfreut.%} ddddd'
pattern = r'{%.*?%}'  # we use ? for non-greedy quantifier

def FUNCTION_new_pattern (pattern):
# I am not sure about re.findall, but the idea to chech if a pattern includes {#.+#}
 x = re.findall(r'{#.+#}', pattern)
 if (x):
  new pattern = r'({%.+)%}({#.+#}){%(.+%})' # I don't know if it will work (my idea - to show 3 groups and new symbols %} {% 
 else:
  new pattern = pattern
    
newstring =  re.sub(pattern, FUNCTION_new_pattern, line)
```

**Comment by funderburkjim** [comment]
@AnnaRybakovaT   Try out the test5.py program.

Readme provides basic usage.
Exercise 1:  Try to match patterns beginning with `{%` and ending with `%}`.  
What pattern to use so that there is one match group containing the text between `{%` and `%}`. 

Exercise 2: find PATTERN that matches 3 parts of LINE `blah {%XX {#YY#} ZZ%} more blah` and similar lines.
has as its 3 match groups `XX `  and  `YY` and ` ZZ`  (note the space ending the X group, and the space beginning the Z group.

Exercise 3:  With the PATTERN of exercise 2, what do you get if LINE is `blah {%XX {#YY#}, ZZ%} more blah`  ?
Note the comma after `{#YY#}` ?  Try different things for XX, etc.

Play around with many PATTERN LINE combos to help you get comfortable with regex pattern matching and match groups.

**Comment by drdhaval2785** [comment]
@AnnaRybakovaT 

If you want to fiddle with regular expressions to understand how they capture the strings, you can try https://regexr.com/

**Comment by AnnaRybakovaT** [comment]
> Play around with many PATTERN LINE combos to help you get comfortable with regex pattern matching and match groups.

Dear Jim,
Thanks for the above exercises and test5.py I have found a pattern which helped to construct the "different lines" by the most optimal way (please see files test6.py and result6.txt).

**Comment by AnnaRybakovaT** [comment]
> Try to match patterns beginning with `{%` and ending with `%}`.
> What pattern to use so that there is one match group containing the text between `{%` and `%}`.

({%.*?%}) -> m.group(1) |{%XX {#YY#} ZZ%}|
{%(.*?)%} -> m.group(1) |XX {#YY#} ZZ|
({%.+)({#.+#})(.+%})  -> m.group(1) |{%XX | m.group(2) |{#YY#}| m.group(3) | ZZ%}|
{%(.+\s)({#.+#})(\s.+)%} -> m.group(1) |XX | m.group(2) |{#YY#}| m.group(3) | ZZ|

**Comment by AnnaRybakovaT** [comment]
> Exercise 3: With the PATTERN of exercise 2, what do you get if LINE is `blah {%XX {#YY#}, ZZ%} more blah` ?
> Note the comma after `{#YY#}` ? Try different things for XX, etc.

{%(.+\s)({#.+#}.*)(\s.+)%}  -> m.group(1) |XX | m.group(2) |{#YY#},| m.group(3) | ZZ|

**Comment by AnnaRybakovaT** [comment]
> `newstring = re.sub(pattern, FUNCTION, string)` This is the form.

Dear Jim,
I stuck with the file change_test.py I am thinking how to use this form and the pattern {%.*?%} 
Now I only put the function from test6.py. Could you give me some ideas regarding next steps, please.

**Comment by AnnaRybakovaT** [comment]
> If you want to fiddle with regular expressions to understand how they capture the strings, you can try https://regexr.com/

Dear Dhaval,
Thank you very much!

**Comment by funderburkjim** [comment]
@AnnaRybakovaT  Based on your test6/result6 -- looks like you found a solution with re.sub.
I like the use of `\s` and `\S` -- I had not thought of that idea.

When I tried `python change_test.py temp_pw_0.txt temp_change_test.yxy`,  the program was
taking too long.

So I made change_test1.py , which 
* in effect, stops changing after the first 10
* Adds square-bracket markup to the NEWLINE part of output  (`[[...]]`) so we can better see
  what the replacement is doing.

Look at change_test1.txt.
You'll see that the replacement is changing many that it should not.
e.g. `{%XX%} {#YY#} {%ZZ%}` is being changed.

Tested this further with test5.py
```
 python test5.py "{%(.+\S)(.*\s?{#.+#}.*\s)(.+)%}" " ... {%italic text%} {#sanskrit text#} blah {%more italic text%}"
LINE | ... {%italic text%} {#sanskrit text#} blah {%more italic text%}|
PATTERN |{%(.+\S)(.*\s?{#.+#}.*\s)(.+)%}|
m.group(0) |{%italic text%} {#sanskrit text#} blah {%more italic text%}|
PATTERN has 3 match groups
m.group(1) |italic text%}|
m.group(2) | {#sanskrit text#} blah {%more italic |
m.group(3) |text|

```

Suggestion:  Maybe `[^%]` can solve this problem ?

Experiment some (using test5) to revise your pattern.
Then, make a change_test2.py  that uses your revised pattern and/or repl. 
Does output look right now ?  (We'll remove the `[[...]]` later)

**Comment by AnnaRybakovaT** [comment]
> Suggestion: Maybe `[^%]` can solve this problem ?

Dear Jim,
Please, help...

I would like to use in a pattern `[^%]` - in group1 or after group1 (just make tests) because I don't wanna the part {%italic text%} matches group1 of this pattern. but it doesn't work:
```
$ python test5.py "{%(.+[^%][^}]\S)(.*\s?{#.+#}.*\s)(.+)%}" " ... {%italic text%} {#sanskrit text#} blah {%more italic text%}"
LINE | ... {%italic text%} {#sanskrit text#} blah {%more italic text%}|
PATTERN |{%(.+[^%][^}]\S)(.*\s?{#.+#}.*\s)(.+)%}|
m.group(0) |{%italic text%} {#sanskrit text#} blah {%more italic text%}|
PATTERN has 3 match groups
m.group(1) |italic text%}|
m.group(2) | {#sanskrit text#} blah {%more italic |
m.group(3) |text|
```
Maybe we can avoid this problem by other way - if we exclude from the beginning all italic cases without Sanskrit text {%italic text%} and we will construct one pattern only for strings {%italic text {#sanskrit text#}  more italic text%}. 
Probably for this reason you suggested above this method:
newstring =  re.sub(pattern, FUNCTION, line)

I don't know - if it has sence (a program with those functions doesn't run):
```
def FUNCTION_new_pattern(line):
 pattern = r'{%(.+\S)(.*\s?{#.+#}.*\s)(.+)%}'
 repl = r'{%\1%}\2{%\3%}'
 newline = re.sub(pattern,repl,line)

def change_one_line(line):
 pattern = r'{%.*?%}'
 newline =  re.sub(pattern, FUNCTION_new_pattern, line)
 return newline
```

**Comment by AnnaRybakovaT** [comment]
Dear Jim,
I have to make a break for a week. Tomorrow we are going to Athens to visit some exhibitions and to place orders for new tourist season. If everything be fine I am coming back home on next Wednesday.

**Comment by funderburkjim** [comment]
test7.py doesn't run because the parameter of the repl function is treated as Match object, not a string.

test8.py provides one way to rewrite the repl function.
It is run with both test1.txt and test8a.txt as example files.  See readme.txt for usage details

change_test2.py modifies change_test1.py, using the ideas of test8  (i.e., use of repl function to
modify text fragments `{%..%}`).
The result file, for debugging purposes,
* is limited to 10 cases
* has changed text enclosed in `[[...]]`  

@AnnaRybakovaT   When you're back,  after studying the above, then 
* write change_test3.py  based on change_test2.py 
  * remove the 10-limit.  
  * document usage in readme.txt
* run change_test3
  * Examine all the changes -- I expect about 235 lines changed.
     * If there are drastically more changes,  don't examine all of them!
  * Note any changes that are wrong 
* Are we ready for final step ?

**Comment by AnnaRybakovaT** [comment]
> When you're back, after studying the above, then

Dear Jim,
I am at home. On Monday I will be able to do all mentioned above steps.

**Comment by AnnaRybakovaT** [comment]
> run change_test3
> 
>     * Examine all the changes -- I expect about 235 lines changed.
>       
>       * If there are drastically more changes,  don't examine all of them!
> 
>     * Note any changes that are wrong

Dear Jim,
Please check the change_test3.py
```
change_test3.txt  (223 changes in 184 entries)
```
After examination of all changes I didn't find any wrong cases.

**Comment by AnnaRybakovaT** [comment]
As you will notice I did some changes in the file test8.py - it is about only to one typo in two comment.

**Comment by funderburkjim** [comment]
change_test3.txt looks good.
Only 2.5 things remain:

## 1. get rid of debugging [[...]]
Let's call the 'final' change program change_1.py. Start with a copy of change_test3.py
```
cp change_test3.py change_1.py
```
Manually edit change_1.py
* remove the place where `[[...]]` in inserted -- these were just for debugging.
* modify comments as needed
* modify readme.txt to indicate how change_1.py differs from change_test3.py

## 2. generate change_1.txt
Per usage directions in readme.txt

## 2.5  Get the latest temp_pw_0.txt and rerun 
I happened to notice that your version of temp_pw_0.txt is not the latest.
* I assume you have a clone of csl-orig repository on your machine.
* cd to csl-orig, and do a `git pull` to get the latest.
* replace `issue91/temp_pw_0.txt` with the revised csl-orig/v02/pw/pw.txt
* rerun change_1.py, thereby revising change_1.txt.

I think change_1.txt should complete preparation of the change file for our issue91.
Then push.

**Comment by funderburkjim** [comment]
> Then push.

That is, add and push the pwk repository

**Comment by AnnaRybakovaT** [comment]
> I happened to notice that your version of temp_pw_0.txt is not the latest.

Dear Jim,
I have updated the repository csl-orig and I see that pw.txt hase a date 12.01.2021 (is it the latest version?)
```
Rybakova@ST-Rybakova MINGW64 ~/Documents/cologne/csl-orig (master)
$ git pull
Already up to date.
```

**Comment by funderburkjim** [comment]
Anna - 
Do a 'git log' in csl-orig.
The top (most recent) commit should show:
```
commit 1f1daf94f18e008af3a9ea8f892df6e9fd2734f7 (HEAD -> master, origin/master, origin/HEAD)
Author: funderburkjim <funderburkjim@gmail.com>
Date:   Mon Jan 23 17:53:16 2023 -0500

    PWG: numeric orphans, 5
    Ref: https://github.com/sanskrit-lexicon/PWG/issues/65
```

**Comment by AnnaRybakovaT** [comment]
> Do a 'git log' in csl-orig

I have:
```
Rybakova@ST-Rybakova MINGW64 ~/Documents/cologne/csl-orig (master)
$ git log
commit ae8dc65fa97abd1f3d7e89309ad1d288704a5160 (HEAD -> master, origin/master, origin/HEAD)
Author: AnnaRybakovaT <arybakovatheohari@gmail.com>
Date:   Sat Mar 6 15:38:43 2021 +0400

    pe.txt - Batch 3

commit 0ebb8d7f523c0b9038b389cd5421b4c44135e4f2
Merge: 6b45d9d e1e11ad
Author: AnnaRybakovaT <74726889+AnnaRybakovaT@users.noreply.github.com>
Date:   Sat Mar 6 14:34:05 2021 +0300

    Merge pull request #6 from sanskrit-lexicon/master

    06.02.2021

commit e1e11ad00eddc9e0ee20ac98c5f0c706959ccac0
Author: funderburkjim <funderburkjim@gmail.com>
Date:   Thu Mar 4 18:02:05 2021 -0500

    mw: Minor correction at L=37689, 43347

commit 47c60b13702e63699e80d7c477650a4fc9529cbe
Author: funderburkjim <funderburkjim@gmail.com>
```

**Comment by funderburkjim** [comment]
## get latest csl-orig
Your 'csl-orig' is definitely not in sync.  I'm not sure where it comes from. We can investigate that later.

For now, get the latest csl-orig from github.
* rename your ~/Documents/cologne/csl-orig  to ~/Documents/cologne/csl-orig-anna 
   * so we can investigate later.
* cd ~/Documents/cologne/
* git clone https://github.com/sanskrit-lexicon/csl-orig.git
   * Do you see know how to get this parameter for git clone?
   * This should give you a new ~/Documents/cologne/csl-orig 
* As check, cd ~/Documents/cologne/csl-orig  and do 'git log' again.
   * yours should agree with mine


Now, 
* copy csl-orig/v02/pw/pw.txt to your issue91 location
* rerun change_1
* push, etc. your pwk repository.

**Comment by AnnaRybakovaT** [comment]
> As check, cd ~/Documents/cologne/csl-orig and do 'git log' again.
> 
>     * yours should agree with mine

Now it is the same
```
Rybakova@ST-Rybakova MINGW64 ~/Documents/cologne/csl-orig (master)
$ git log
commit 1f1daf94f18e008af3a9ea8f892df6e9fd2734f7 (HEAD -> master, origin/master, origin/HEAD)
Author: funderburkjim <funderburkjim@gmail.com>
Date:   Mon Jan 23 17:53:16 2023 -0500

    PWG: numeric orphans, 5
    Ref: https://github.com/sanskrit-lexicon/PWG/issues/65
```

**Comment by funderburkjim** [comment]
@AnnaRybakovaT 
The changes of change_1.txt now look fine.
They have been installed.  (see readme.txt section after change_1.txt for details.)

OUR WORK IS FINISHED for this issue :)

Investigate: where did csl-orig-anna come from?
* cd to csl-orig-anna
* git remote -v
  * The output may provide a clue

**Comment by AnnaRybakovaT** [comment]
> * The output may provide a clue

Dear Jim,
please, see the output:
```
Rybakova@ST-Rybakova MINGW64 ~/Documents/cologne/csl-orig-anna (master)
$ git remote -v
origin  https://github.com/AnnaRybakovaT/csl-orig.git (fetch)
origin  https://github.com/AnnaRybakovaT/csl-orig.git (push)
```

**Comment by funderburkjim** [comment]
@AnnaRybakovaT   Not sure if the csl-orig at your github account has further use.
Perhaps it was made as part of a workflow with @drdhaval2785.

**Comment by drdhaval2785** [comment]
It is Anna’s fork of csl-orig repository.

**Comment by drdhaval2785** [comment]
Anna can delete this repository without any information loss. Forked repositories are useful if we want to create pull requests.

**Comment by AnnaRybakovaT** [comment]
> Anna can delete this repository without any information loss.

Thanks!
