### ISSUE TITLE
Chrestomathy ls markup

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/PWK#93]
There are about 6000 PWK numeric ls references.
The second paragraph from [this front matter page](https://sanskrit-lexicon.uni-koeln.de/scans/csldev/csldoc/build/dictionaries/prefaces/pwpref/pwpref03.html) translates as

> In conclusion, I list the works cited in this first part. 
**Two numbers without specifying a book refer to the second edition of my chrestomathy.** 
The name in parentheses at the end of a title designates the scholar who made all or most of the contributions to this dictionary from the book indicated.

Markup needs to be enhanced for these, in order that tooltip will be available for these.

We may also choose to add links.

**Comment by funderburkjim** [comment]
In case we decide to make a link target, one potential source is
https://archive.org/details/sanskritchresto01bhgoog/page/n11/mode/2up

There may be a better source at Bayerische StaatsBibliothek  (see links for mbh at [this comment](https://github.com/sanskrit-lexicon/COLOGNE/issues/371#issuecomment-1001463025)).

**Comment by funderburkjim** [comment]
I think there is a version at BSB, but couldn't find the exact link for downloading.  Probably @Andhrabharati can find the download link.

**Comment by funderburkjim** [comment]
Great!  Thank you!

**Comment by funderburkjim** [comment]
## changes now installed.

Work is in [issue93 directory](https://github.com/sanskrit-lexicon/PWK/tree/master/pwkissues/issue93).

* lsextract_pw_0.txt shows counts of the various ls categories for pw *before* the changes
* change_1.txt has all the changes.  Over 5000
* lsextract_pw_1.txt shows counts of the various ls categories for pw *after* the changes
* only a handful of `<ls>number` instances
  * Includes the 'Harisv.' correction mentioned in #79 comment above.
  * still has 23 'UNKNOWN' ls references.  They will need to be investigated some other time.
* Due to methodology (automatic replacement of certain patterns),  likely some of the
   instances marked as `<ls n="Chr.">` will be wrong -- but probably not many :)

My next step will be to make a link target for Chrestomathie.

**Comment by Andhrabharati** [comment]
> * still has 23 'UNKNOWN' ls references.  They will need to be investigated some other time.

@funderburkjim 

would you list these 23 items?-- so that I can see if they can be resolved (of course, if you wish me to!)

**Comment by funderburkjim** [comment]
## link target
https://sanskrit-lexicon-scans.github.io/bchrest/index.html is link target for Boehtlingk Chrestomathie, 2nd edition.

Need to add this (and the rest of current link targets) to link tracker at https://github.com/sanskrit-lexicon/COLOGNE/issues/390.

**Comment by funderburkjim** [comment]
@Andhrabharati   Here's that list of unknown ls (along with 5 or so 'number' ls).

[ls_num_and_unknown.txt](https://github.com/sanskrit-lexicon/PWK/blob/master/pwkissues/issue93/ls_num_and_unknown.txt)
has 28 `<ls>` cases where either the abbreviation is unknown (no tooltip) or the ls element starts with a number.

**Comment by Andhrabharati** [comment]
@funderburkjim 

Here are the resp. entries (in no particular order)--

1. pl. recall that S. is Seite (page) and Z. is Zeile (line) were already deciphered earlier. This should resolve the "; problem with: S." cases [9 nos.]
2. Kadambari of Banabhatta is in two parts (Purva & Uttara), and the II denotes the 2nd half of Kadambari. This should resolve the "; problem with: II," cases [10 nos.]
3. "; problem with: Hariv. 9940." denotes the verse 9940 of Harivamsa. [1 no.]
4. "; problem with: 2, S. 40" denotes the ch. 2 p.40 (cf. "S." denoting 'page' in 1 above) [1 no.]
5. "; problem with:  R. 1,1,55" is the Gorr. Ramayana (cf. PWG entry for the same HW)  [1 no.]
6. "; problem with: 772" and "; problem with: 58" denote the verses in Medinikosa in resp. letter varga. [2 nos.]
7. "; problem with: 30." the 30 should be padded with "BĀDAR. 2,2," [1 no.]
8. "; problem with: 1,31,13." refers to Āpastamba Dharmasūtra 1.31.13 [1 no.]
9. "; problem with:  VP. 6,4,29." refers to the Vishnu Purana Bombay ed. [1 no.]
10. what's the "; problem with: MAITR. 4,9,5."? the same citation appears at three places just above this entry! [1 no.]
![image](https://user-images.githubusercontent.com/75209130/229901698-9b0bb47f-9ff9-49bc-9c60-c8156a121d41.png)

**Comment by funderburkjim** [comment]
## Question re Medinikosa 
The references in PW are generally like `<ls>MED. k. 13</ls>` which occurs under headword DUmaka
```
{#DUmaka#}¦
<div n="1">— 1) am Ende eines <lex>adj.</lex> Comp. = {#DUma#} {%Rauch.%}
<div n="1">— 2) <lex>m.</lex> {%eine <ab>best.</ab> Gemüsepflanze%} <ls>CARAKA. 1,27.</ls>
<div n="1">— 3) <lex>f.</lex> {#DUmikA#}
<div n="2">— a) {%Rauch.%}
<div n="2">— b) {%*Nebel.%}
<div n="2">— c) <ls>MED. k. 13</ls> fehlerhaft für {#BUmikA#}.
```
I expected 'k. 13' to relate to 
<img width="458" alt="image" src="https://user-images.githubusercontent.com/6393033/230650692-c8a3f397-0756-4633-9c84-bce8142771ba.png">

https://archive.org/details/MediniKoshaJagannathSastriChaukhamba/page/n7/mode/2up ?

But none of  'DUmaka, DUmikA, BUmikA'  is found there.
What am I missing?

**Comment by funderburkjim** [comment]
Changes made based on @Andhrabharati suggestions (Thanks for those!).

**Comment by Andhrabharati** [comment]
> ## Question re Medinikosa
> 
> The references in PW are generally like `<ls>MED. k. 13</ls>` which occurs under headword DUmaka
> 
> ```
> {#DUmaka#}¦
> <div n="1">— 1) am Ende eines <lex>adj.</lex> Comp. = {#DUma#} {%Rauch.%}
> <div n="1">— 2) <lex>m.</lex> {%eine <ab>best.</ab> Gemüsepflanze%} <ls>CARAKA. 1,27.</ls>
> <div n="1">— 3) <lex>f.</lex> {#DUmikA#}
> <div n="2">— a) {%Rauch.%}
> <div n="2">— b) {%*Nebel.%}
> <div n="2">— c) <ls>MED. k. 13</ls> fehlerhaft für {#BUmikA#}.
> ```
> 
> I expected 'k. 13' to relate to <img alt="image" width="458" src="https://user-images.githubusercontent.com/6393033/230650692-c8a3f397-0756-4633-9c84-bce8142771ba.png">
> 
> https://archive.org/details/MediniKoshaJagannathSastriChaukhamba/page/n7/mode/2up ?
> 
> But none of 'DUmaka, DUmikA, BUmikA' is found there. What am I missing?

You did miss it for a reason, @funderburkjim ; it's because pwk is having a print error (13 instead of 134) here!

pwk has the entry as
![image](https://user-images.githubusercontent.com/75209130/230659738-66a0d602-4b31-4abe-a21e-bd52d4a64cb6.png)

and PWG has the entry as
![image](https://user-images.githubusercontent.com/75209130/230659833-95ecd19c-9cc7-412e-89cb-aa35f3e45d07.png)

and here is the Medinikosa ed. referred in PWG (GILD. Bibl. 256), having the error (**DUmikA for BUmikA**)
![image](https://user-images.githubusercontent.com/75209130/230660916-44f6b347-4a60-4a4b-9e26-60ab811a4722.png)

And here is the Medinikosa snippet (Med. k. 135) from the Chowkhamba ed. you referred--
![image](https://user-images.githubusercontent.com/75209130/230660049-e0bb9c7e-78fc-4b1d-ab39-df3face48f41.png)

Finally, here is a Bengali Medinikosa ed. having the verse (Med. k. 134) cited--
![image](https://user-images.githubusercontent.com/75209130/230661444-80b10ca9-7f83-4cc0-9f15-7cfc9072f207.png)

**Comment by funderburkjim** [comment]
@Andhrabharati  thank you for helpful analysis that '13' should be '134'.

This is a *typo* (digitization error in cdsl pw.txt), since PW scan also shows 134.   
<img width="381" alt="image" src="https://user-images.githubusercontent.com/6393033/230932873-59942f79-45b3-4c81-a1d7-2af127279e51.png">

```
cdsl OLD:
<div n="2">— c) <ls>MED. k. 13</ls> fehlerhaft für {#BUmikA#}.
NEW:
<div n="2">— c) <ls>MED. k. 134</ls> fehlerhaft für {#BUmikA#}.
```

Correction to pw.txt made -- added to change_2.txt.

**Comment by gasyoun** [comment]
@funderburkjim https://vk.com/samskrtamru?w=wall-88831040_18144 here is my scan of it.

**Comment by Andhrabharati** [comment]
@gasyoun 
I recall your earlier saying that  almost all the Sanskrit collection/Reader (Chrestomathie) works scanned afresh would be available with you this year.

Is this a beginning of making them public?

**Comment by gasyoun** [comment]
> Is this a beginning of making them public?

Yes.

> almost all the Sanskrit collection/Reader (Chrestomathie)

Depends on which you are looking for. I know them all (have made a comparison table of all Sanskrit readers in 2013, when was releasing the Reader of my teacher), but have scanned not all, nor have a good source for all of them.
